trigger:
  - "main"

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
  displayName: 'Use Python 3.9'

- script: |
    python -m pip install --upgrade pip
    python -m pip install --upgrade build setuptools twine
    python -m build
  displayName: 'Install dependencies and build'


- task: TwineAuthenticate@1
  inputs:
    artifactFeed: dss

- script: |
   twine upload -r "dss" --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Publish artifact'