FROM python:3.9

ADD . /api
WORKDIR /api

# for local secret propagation you can use this as a  reference: 
# https://medium.com/devops-dudes/using-private-python-azure-artifacts-feeds-in-alpine-docker-builds-909e6558c1a4
# be aware this is not very secure and should be used very accurately
RUN PRIVATE_PIP_AZURE_ARTIFACTS_URL=$(cat pip.url.secret) && \
    pip install -r requirements.txt --extra-index-url=${PRIVATE_PIP_AZURE_ARTIFACTS_URL}  

# start the server
CMD ["uvicorn", "main:app", "--port", "5000", "--host", "0.0.0.0"]
